
copy:
	cp -f ./Dependencies/lib/$(LibDir)/libGCC/*.* ./lib/$(LibDir)/.

all:
	make -C NSGUI all
	make -C 2DAnimation all
	make -C SimpleTexture all
	make -C SimpleEffect all
	make -C SimpleMesh all
	make -C 3DAnimation all
	make -C 3DAnimation2 all
	make -C DrawDX11Triangle all
	make -C DrawDX11TexturedQuad all
	make -C opengl_simple all
	make -C Road01 all
	make -C Road02 all
	make -C TestNoise all
	make -C BallOfFire all
	make -C VTF all

clean:
	make -C NSGUI clean
	make -C 2DAnimation clean
	make -C SimpleTexture clean
	make -C SimpleEffect clean
	make -C SimpleMesh clean
	make -C 3DAnimation clean
	make -C 3DAnimation2 clean
	make -C DrawDX11Triangle clean
	make -C DrawDX11TexturedQuad clean
	make -C opengl_simple clean
	make -C Road01 clean
	make -C Road02 clean
	make -C TestNoise clean
	make -C BallOfFire clean
	make -C VTF clean
