all:
	CALL C:\\Python27\\python.exe C:\\DesktopProjects\\setup.py install

clean:
	DEL /S /Q *.pyc *.obj C:\\build C:\\DesktopProjects\\build

test:
	CALL C:\\Python27\\python.exe C:\\DesktopProjects\\test.py

uninstall:
	DEL /S /Q C:\\Python27\\Lib\\site-packages\\initVulkan3.so
	DEL /S /Q C:\\Python27\\Lib\\site-packages\\initVulkan3-1.0-py2.7.egg-info


