--file = "/masters-grammar-interpreter/testing.txt"
--file = "/masters-grammar-interpreter/borg_cube.txt"
--file = "/masters-grammar-interpreter/c_station.txt"
--file = "/masters-grammar-interpreter/enterprise.txt"
--file = "/masters-grammar-interpreter/klingon.txt"
--file = "/masters-grammar-interpreter/rotational_ship.txt"
--file = "/masters-grammar-interpreter/space_station.txt"
--file = "/masters-grammar-interpreter/spike_ship.txt"
--file = "/masters-grammar-interpreter/squid_ship.txt"
file = "/masters-grammar-interpreter/tie_fighter.txt"
--file = "/masters-grammar-interpreter/wing_ship.txt"

