struct vertex2fragment { 
	float4 Position : POSITION;
	float2 TexCoord : TEXCOORD0;
	float3 LightDir : TEXCOORD1;
	float3 EyeVec : TEXCOORD2;
	float4 Color : COLOR0;
};


float4 main (vertex2fragment IN,
	uniform float4 lightcolor,
	uniform sampler2D TexDiffuse : TEXUNIT0,
	uniform sampler2D TexNormal : TEXUNIT1,
	uniform sampler2D TexHeight : TEXUNIT2) : COLOR
{
    //IN.Color += tex2D (TexNormal, IN.TexCoord)
	//return tex2D (TexDiffuse, IN.TexCoord) * IN.Color;
	
	return lightcolor;
}
