chmod a+x ./test.sh &&
chmod a+x ./Dependencies/Mali_OpenGL_ES_Emulator-v3.0.2.g694a9-Linux-32bit/linux-install.sh &&
chmod a+x ./DesktopProjects/NDK_gl_code2/androidbuild3.sh &&
chmod a+x ./DesktopProjects/NDK_gl_code2/androidbuild.sh &&
chmod a+x ./DesktopProjects/NDK_SDL2/androidbuild3.sh &&
chmod a+x ./DesktopProjects/NDK_SDL2/androidbuild.sh &&
chmod a+x ./DesktopProjects/iOS/assets.sh &&
chmod a+x ./DesktopProjects/iOS/iOS_resources.sh &&
chmod a+x ./DesktopProjects/iOS/runsim.sh &&
chmod a+x ./DesktopProjects/iOS/createframework.sh &&
chmod a+x ./make.sh &&
chmod a+x ./install_.sh &&
chmod a+x ./bastet.sh &&
chmod a+x ./runIL.sh &&
chmod a+x ./installV.sh &&
chmod a+x ./rmlibs.sh &&
chmod a+x ./OS.sh &&
chmod a+x ./install.sh &&
chmod a+x ./Tanks.sh &&
chmod a+x ./3D.sh &&
chmod a+x ./glslangValidator.sh &&
chmod a+x ./lexxyacc.sh &&
chmod a+x ./mk/NS.sh &&
chmod a+x ./mk/testArray.sh &&
chmod a+x ./mk/toIL.sh &&
chmod a+x ./mk/testlipo.sh &&
chmod a+x ./mk/gedit.sh &&
chmod a+x ./GLES3.sh &&
chmod a+x ./HLSLparser2.sh &&
chmod a+x ./Docs/make/make.sh &&
chmod a+x ./Docs/low-level/Vulkan/spirv_cross/spirv_cross.sh &&
chmod a+x ./Docs/low-level/low-level/Vulkan/Vulkan.sh &&
chmod a+x ./Docs/hlslparser/cgc.sh &&
chmod a+x ./Docs/hlslparser/hlslparser.sh &&
chmod a+x ./Docs/shaders/fxc/fxc.sh &&
chmod a+x ./Docs/JavaJNI/run2.sh &&
chmod a+x ./Docs/JavaJNI/run.sh &&
chmod a+x ./reconfigurexorg.sh &&
chmod a+x ./spirv_cross.sh &&
chmod a+x ./HLSLparser.sh &&
chmod a+x ./x.sh &&
chmod a+x ./python.sh &&
chmod a+x ./gedit.sh &&
chmod a+x ./updategit.sh &&
chmod a+x ./CopyLibraries.sh &&
chmod a+x ./run_interpreter.sh &&
chmod a+x ./find.sh &&
chmod a+x ./runOSX.sh &&
chmod a+x ./screenshots/testgles2.sh &&
chmod a+x ./screenshots/sudoaptgetinstall.sh &&
chmod a+x ./clean.sh &&
chmod a+x ./run.sh 
