Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Framework", "DesktopProjects\projectsX\Framework\Framework.vcxproj", "{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "SimpleTexture", "DesktopProjects\projectsX\SimpleTexture\SimpleTexture.vcxproj", "{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC902}"
	ProjectSection(ProjectDependencies) = postProject
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901} = {8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "SimpleEffect", "DesktopProjects\projectsX\SimpleEffect\SimpleEffect.vcxproj", "{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC903}"
	ProjectSection(ProjectDependencies) = postProject
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901} = {8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "3DAnimation2", "DesktopProjects\projectsX\3DAnimation2\3DAnimation2.vcxproj", "{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC904}"
	ProjectSection(ProjectDependencies) = postProject
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901} = {8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Win32 = Debug|Win32
		Release|Win32 = Release|Win32
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}.Debug|Win32.ActiveCfg = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}.Debug|Win32.Build.0 = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}.Release|Win32.ActiveCfg = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC901}.Release|Win32.Build.0 = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC902}.Debug|Win32.ActiveCfg = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC902}.Debug|Win32.Build.0 = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC902}.Release|Win32.ActiveCfg = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC902}.Release|Win32.Build.0 = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC903}.Debug|Win32.ActiveCfg = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC903}.Debug|Win32.Build.0 = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC903}.Release|Win32.ActiveCfg = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC903}.Release|Win32.Build.0 = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC904}.Debug|Win32.ActiveCfg = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC904}.Debug|Win32.Build.0 = Debug|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC904}.Release|Win32.ActiveCfg = Release|Win32
		{8BC9CEB8-8B4B-11D7-8D12-00A0C91BC904}.Release|Win32.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
