cd ./bin;./R2VB-Footprint.bin;cd .. &&
cd ./bin;./R2VB-IK.bin;cd .. &&
cd ./bin;./R2VB-OceanWater.bin;cd .. &&
cd ./bin;./InfiniteTerrainII.bin;cd .. &&
cd ./bin;./R2VB-Animation.bin;cd .. &&
cd ./bin;./R2VB-Cloth.bin;cd .. &&
cd ./bin;./R2VB-Collision.bin;cd .. &&
cd ./bin;./R2VB-NPatches.bin;cd .. &&
cd ./bin;./R2VB-ParticleSystem.bin;cd .. &&
cd ./bin;./R2VB-ShadowVolume.bin;cd .. &&
cd ./bin;./R2VB-Sort.bin;cd .. &&
cd ./bin;./R2VB-TerrainMorph.bin;cd .. &&
cd ./bin;./R2VB-Water.bin;cd .. &&
cd ./bin;./Skinning10.bin;cd .. &&
cd ./bin;./RaycastTerrain.bin;cd .. &&
cd ./bin;./DeferredParticles.bin;cd .. &&
cd ./bin;./Island11.bin;cd .. &&
cd ./bin;./Rain.bin;cd .. &&
cd ./bin;./VTF.bin;cd .. &&
cd ./bin;./InfiniteTerrainII.bin;cd .. &&
cd ./bin;./apptreeview.bin;cd .. &&
cd ./bin;./XFile.bin;cd .. &&
cd ./bin;./ProceduralBuilding.bin;cd .. &&
cd ./bin;./ProceduralHouse.bin;cd .. &&
cd ./bin;./ProceduralHouse2.bin;cd .. &&
cd ./bin;./ProceduralHouse3.bin;cd .. &&
cd ./bin;./2DAnimation.bin;cd .. &&
cd ./bin;./testspine2.bin;cd .. &&
cd ./bin;./Stars.bin;cd .. &&
cd ./bin;./Blender_3DS.bin;cd .. &&
cd ./bin;./masters-grammar-interpreter.bin;cd .. &&
cd ./bin;./CantorDust3D5.bin;cd .. &&
cd ./bin;./CantorDust3D3.bin;cd .. &&
cd ./bin;./NatureScene2.bin;cd .. &&
cd ./bin;./Blender_3DS.bin;cd .. &&
cd ./bin;./CantorDust3D5.bin;cd .. &&
cd ./bin;./TexturedCube.bin;cd .. &&
cd ./bin;./3DAnimation.bin;cd ..