cd ./bin;./BallOfFire.bin;cd .. &&
cd ./bin;./TestNoise.bin;cd .. &&
cd ./bin;./pbr.bin;cd .. &&
cd ./bin;./teapots_8c.bin;cd .. &&
cd ./bin;./DirectionalLighting.bin;cd .. &&
cd ./bin;./MultiLighting.bin;cd .. &&
cd ./bin;./SpotLighting.bin;cd .. &&
cd ./bin;./PhongLighting2.bin;cd .. &&
cd ./bin;./PhongLighting1.bin;cd .. &&
cd ./bin;./DiffuseLighting.bin;cd .. &&
cd ./bin;./AmbientLighting.bin;cd .. &&
cd ./bin;./12_Explosion_Particle_Effect.bin;cd .. &&
cd ./bin;./2DAnimation.bin;cd .. &&
cd ./bin;./3DAnimation.bin;cd .. &&
cd ./bin;./3DAnimation2.bin;cd .. &&
cd ./bin;./3DAnimation5.bin;cd .. &&
cd ./bin;./3DAnimation6.bin;cd .. &&
cd ./bin;./AccurateAtmosphericalScattering.bin;cd .. &&
cd ./bin;./AtlasTexture.bin;cd .. &&
cd ./bin;./AtlasTexture2.bin;cd .. &&
cd ./bin;./AtlasTexture3.bin;cd .. &&
cd ./bin;./Billboard.bin;cd .. &&
cd ./bin;./Billboard2.bin;cd .. &&
cd ./bin;./Blending.bin;cd .. &&
cd ./bin;./CantorDust2D.bin;cd .. &&
cd ./bin;./CantorDust3D3.bin;cd .. &&
cd ./bin;./CantorDust3D5.bin;cd .. &&
cd ./bin;./Clock_Dial.bin;cd .. &&
cd ./bin;./ColoredCube.bin;cd .. &&
cd ./bin;./DDSAnimation.bin;cd .. &&
cd ./bin;./Digital_Clock.bin;cd .. &&
cd ./bin;./DirtTexture.bin;cd .. &&
cd ./bin;./Effect.bin;cd .. &&
cd ./bin;./Effect2.bin;cd .. &&
cd ./bin;./Fibonacci.bin;cd .. &&
cd ./bin;./Fibonacci2.bin;cd .. &&
cd ./bin;./HLSL-noise.bin;cd .. &&
cd ./bin;./HLSL-noise2.bin;cd .. &&
cd ./bin;./InfiniteTerrain.bin;cd .. &&
cd ./bin;./L_System2D.bin;cd .. &&
cd ./bin;./L_System3D.bin;cd .. &&
cd ./bin;./L_System3D2.bin;cd .. &&
cd ./bin;./NormalMapping.bin;cd .. &&
cd ./bin;./Parabola.bin;cd .. &&
cd ./bin;./ParticleVS.bin;cd .. &&
cd ./bin;./ParticleVS3.bin;cd .. &&
cd ./bin;./PerlinFire.bin;cd .. &&
cd ./bin;./ProceduralBuilding.bin;cd .. &&
cd ./bin;./ProceduralBuilding5.bin;cd .. &&
cd ./bin;./ProceduralBuilding2.bin;cd .. &&
cd ./bin;./ProceduralBuilding3.bin;cd .. &&
cd ./bin;./ProceduralHouse.bin;cd .. &&
cd ./bin;./ProceduralHouse2.bin;cd .. &&
cd ./bin;./ProceduralHouse3.bin;cd .. &&
cd ./bin;./Quad.bin;cd .. &&
cd ./bin;./RenderMonkey.bin;cd .. &&
cd ./bin;./Shape3D.bin;cd .. &&
cd ./bin;./Shape3D2.bin;cd .. &&
cd ./bin;./Shape3D3.bin;cd .. &&
cd ./bin;./SimpleEffect.bin;cd .. &&
cd ./bin;./SimpleTexture.bin;cd .. &&
cd ./bin;./SimpleTexture2.bin;cd .. &&
cd ./bin;./SimpleTexture3.bin;cd .. &&
cd ./bin;./SimpleTexture4.bin;cd .. &&
cd ./bin;./SimpleTiling.bin;cd .. &&
cd ./bin;./SkyBox.bin;cd .. &&
cd ./bin;./SkyBox2.bin;cd .. &&
cd ./bin;./Stars.bin;cd .. &&
cd ./bin;./Texture.bin;cd .. &&
cd ./bin;./TexturedCube.bin;cd .. &&
cd ./bin;./TexturedCube2.bin;cd .. &&
cd ./bin;./VertexDisplacement.bin;cd .. &&
cd ./bin;./VertexDisplacement2D.bin;cd .. &&
cd ./bin;./cube.bin;cd .. &&
cd ./bin;./dx9u_cgfx_volumetric_lines.bin;cd .. &&
cd ./bin;./masters-grammar-interpreter.bin;cd .. &&
cd ./bin;./maze3D.bin;cd .. &&
cd ./bin;./noise2D.bin;cd .. &&
cd ./bin;./noise3D.bin;cd .. &&
cd ./bin;./noise3D2.bin;cd .. &&
cd ./bin;./testspine2.bin;cd .. &&
cd ./bin;./texturegranite.bin;cd .. &&
cd ./bin;./texturejade.bin;cd .. &&
cd ./bin;./texturesky.bin;cd .. &&
cd ./bin;./textureslime.bin;cd .. &&
cd ./bin;./texturewood.bin;cd .. &&
cd ./bin;./vnoise.bin;cd .. &&
cd ./bin;./a_01_Installing.bin;cd .. &&
cd ./bin;./a_02_IND_Surface.bin;cd .. &&
cd ./bin;./a_03_IND_Image.bin;cd .. &&
cd ./bin;./a_04_IND_Animation.bin;cd .. &&
cd ./bin;./a_05_IND_Font.bin;cd .. &&
cd ./bin;./a_06_Primitives.bin;cd .. &&
cd ./bin;./a_07_IND_Input.bin;cd .. &&
cd ./bin;./a_08_Collisions.bin;cd .. &&
cd ./bin;./a_09_IND_3dMesh.bin;cd .. &&
cd ./bin;./a_10_IND_Light.bin;cd .. &&
cd ./bin;./a_11_Animated_Tile_Scrolling.bin;cd .. &&
cd ./bin;./a_13_2d_Camera.bin;cd .. &&
cd ./bin;./a_14_3d_Camera.bin;cd .. &&
cd ./bin;./a_15_Parallax_Scrolling.bin;cd .. &&
cd ./bin;./a_16_IND_Timer.bin;cd .. &&
cd ./bin;./b_01_IND_Surface_Grids.bin;cd .. &&
cd ./bin;./b_02_Blitting_2d_Directly.bin;cd .. &&
cd ./bin;./b_03_Blitting_3d_Directly.bin;cd .. &&
cd ./bin;./b_04_Several_ViewPorts.bin;cd .. &&
cd ./bin;./c_01_Alien_BenchMark.bin;cd .. &&
cd ./bin;./c_02_Rabbits_BenchMark.bin;cd .. &&
cd ./bin;./IndieLib_Animation_Collision.bin;cd .. &&
cd ./bin;./IndieLib_Blend.bin;cd .. &&
cd ./bin;./IndieLib_Fading.bin;cd .. &&
cd ./bin;./IndieLib_FloatingText.bin;cd .. &&
cd ./bin;./IndieLib_ParallaxScroll.bin;cd .. &&
cd ./bin;./IndieLib_TankEnemies.bin;cd .. &&
cd ./bin;./IndieLib_TankEnemiesParallax.bin;cd .. &&
cd ./bin;./IndieLib_TankFollowsMouseFires.bin;cd .. &&
cd ./bin;./IndieLib_Transitions.bin;cd .. &&
cd ./bin;./RadeonTerrainDemo.bin;cd .. &&
cd ./bin;./NatureScene2.bin;cd .. &&
cd ./bin;./NatureSceneSky.bin;cd ..