cd ./bin;./a_01_Installing.bin;cd .. &&
cd ./bin;./a_02_IND_Surface.bin;cd .. &&
cd ./bin;./a_03_IND_Image.bin;cd .. &&
cd ./bin;./a_04_IND_Animation.bin;cd .. &&
cd ./bin;./a_05_IND_Font.bin;cd .. &&
cd ./bin;./a_06_Primitives.bin;cd .. &&
cd ./bin;./a_07_IND_Input.bin;cd .. &&
cd ./bin;./a_08_Collisions.bin;cd .. &&
cd ./bin;./a_09_IND_3dMesh.bin;cd .. &&
cd ./bin;./a_10_IND_Light.bin;cd .. &&
cd ./bin;./a_11_Animated_Tile_Scrolling.bin;cd .. &&
cd ./bin;./a_13_2d_Camera.bin;cd .. &&
cd ./bin;./a_14_3d_Camera.bin;cd .. &&
cd ./bin;./a_15_Parallax_Scrolling.bin;cd .. &&
cd ./bin;./a_16_IND_Timer.bin;cd .. &&
cd ./bin;./b_01_IND_Surface_Grids.bin;cd .. &&
cd ./bin;./b_02_Blitting_2d_Directly.bin;cd .. &&
cd ./bin;./b_03_Blitting_3d_Directly.bin;cd .. &&
cd ./bin;./b_04_Several_ViewPorts.bin;cd .. &&
cd ./bin;./c_01_Alien_BenchMark.bin;cd .. &&
cd ./bin;./c_02_Rabbits_BenchMark.bin;cd .. &&
cd ./bin;./IndieLib_Animation_Collision.bin;cd .. &&
cd ./bin;./IndieLib_Blend.bin;cd .. &&
cd ./bin;./IndieLib_Fading.bin;cd .. &&
cd ./bin;./IndieLib_FloatingText.bin;cd .. &&
cd ./bin;./IndieLib_ParallaxScroll.bin;cd .. &&
cd ./bin;./IndieLib_TankEnemies.bin;cd .. &&
cd ./bin;./IndieLib_TankEnemiesParallax.bin;cd .. &&
cd ./bin;./IndieLib_TankFollowsMouseFires.bin;cd .. &&
cd ./bin;./IndieLib_Transitions.bin;cd ..

