gedit ../Samples/new/new__/OceanCS/main.cpp&
gedit ../Samples/new/new__/NBody/DX10/NBodyGravity/NBodyGravity.cpp&
gedit ../Samples/new/new/javagames/src/moon_lander/Window.h&
gedit ../Samples/new/new/javagames/src/moon_lander/PlayerRocket.h&
gedit ../Samples/new/new/javagames/src/moon_lander/Game.h&
gedit ../Samples/new/new/javagames/src/moon_lander/LandingArea.h&
gedit ../Samples/new/new/javagames/src/moon_lander/Canvas.h&
gedit ../Samples/new/new/javagames/src/moon_lander/Framework.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Bullet.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Window.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Animation.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/PlayerHelicopter.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Rocket.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/MovingBackground.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Game.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/RocketSmoke.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Canvas.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/EnemyHelicopter.h&
gedit ../Samples/new/new/javagames/src/helicopterbattle/Framework.h&
gedit ../Samples/new/new/javagames/src/shoot_the_duck/Duck.h&
gedit ../Samples/new/new/javagames/src/shoot_the_duck/Window.h&
gedit ../Samples/new/new/javagames/src/shoot_the_duck/Game.h&
gedit ../Samples/new/new/javagames/src/shoot_the_duck/Canvas.h&
gedit ../Samples/new/new/javagames/src/shoot_the_duck/Framework.h&
gedit ../Samples/new/new/GL/hdr/rgbe.h&
gedit ../Samples/new/new/GL/hdr/hdrtexture.cpp&
gedit ../Samples/new/new/GL/hdr/hdr.cpp&
gedit ../Samples/new/new/GL/hdr/blur.cpp&
gedit ../Samples/new/new/GL/hdr/blur.h&
gedit ../Samples/new/new/GL/hdr/hdrtexture.h&
gedit ../Samples/new/new/GL/ParallaxMappingOpenGL/App.cpp&
gedit ../Samples/new/new/GL/ParallaxMappingOpenGL/App.h&
gedit ../Samples/new/new/DX10/GrassInstancing/InstancedBillboard.h&
gedit ../Samples/new/new/DX10/GrassInstancing/BBGrassPatch.h&
gedit ../Samples/new/new/DX10/GrassInstancing/Billboard.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/TerrainPatch.h&
gedit ../Samples/new/new/DX10/GrassInstancing/BillboardedTrees.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/Grass.h&
gedit ../Samples/new/new/DX10/GrassInstancing/BBGrassPatch.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/TerrainPatch.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/Grass.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/Billboard.h&
gedit ../Samples/new/new/DX10/GrassInstancing/InstancedBillboard.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/main.cpp&
gedit ../Samples/new/new/DX10/GrassInstancing/BillboardedTrees.h&
gedit ../Samples/new/new/DX10/SkinAnimation/App.cpp&
gedit ../Samples/new/new/DX10/SkinAnimation/GPUModel.cpp&
gedit ../Samples/new/new/DX10/SkinAnimation/GPUModel.h&
gedit ../Samples/new/new/DX10/SkinAnimation/App.h&
gedit ../Samples/new/new/DX10/FurShellsAndFins/FurShellsAndFins.cpp&
gedit ../Samples/new/new/DX10/FurShellsAndFins/resource.h&
gedit ../Samples/new/new/asteroids/src/Bullet.h&
gedit ../Samples/new/new/asteroids/src/Ship.h&
gedit ../Samples/new/new/asteroids/src/Asteroid.h&
gedit ../Samples/new/new/asteroids/src/GameSprite.h&
gedit ../Samples/new/new/asteroids/src/Game.h&
gedit ../Samples/new/new/asteroids/src/Main.h&
gedit ../Samples/new/new/asteroids/src/Explosion.h&
gedit ../Samples/new/new/DX9/HDRLighting/HDRLighting.cpp&
gedit ../Samples/new/new/DX9/HDRLighting/GlareDefD3D.cpp&
gedit ../Samples/new/new/DX9/HDRLighting/GlareDefD3D.h&
gedit ../Samples/new/new/DX9/HDRPipeline/enumeration.cpp&
gedit ../Samples/new/new/DX9/HDRPipeline/HDRScene.cpp&
gedit ../Samples/new/new/DX9/HDRPipeline/PostProcess.h&
gedit ../Samples/new/new/DX9/HDRPipeline/HDRPipeline.cpp&
gedit ../Samples/new/new/DX9/HDRPipeline/HDRScene.h&
gedit ../Samples/new/new/DX9/HDRPipeline/Luminance.cpp&
gedit ../Samples/new/new/DX9/HDRPipeline/PostProcess.cpp&
gedit ../Samples/new/new/DX9/HDRPipeline/Luminance.h&
gedit ../Samples/new/new/DX9/HDRPipeline/enumeration.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/SpaceShipManager.cpp&
gedit ../Samples/new/new/DX9/HLSL_Instancing/MothershipManager.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/Asteroid.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/AsteroidManager.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/nv_d3d9FullScreenQuad.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/Asteroid.cpp&
gedit ../Samples/new/new/DX9/HLSL_Instancing/SpaceShip.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/AsteroidManager.cpp&
gedit ../Samples/new/new/DX9/HLSL_Instancing/nv_skybox.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/HLSL_Instancing.cpp&
gedit ../Samples/new/new/DX9/HLSL_Instancing/resource.h&
gedit ../Samples/new/new/DX9/HLSL_Instancing/SpaceShipManager.h&
gedit ../Samples/new/new/DX9/HDRFormats/hdrformats.cpp&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Water.cpp&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Mesh.cpp&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Grid.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/HeightMap.cpp&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/dxstdafx.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Viewer.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Vertex.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/registers.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Grid.cpp&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Water.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Mesh.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/HeightMap.h&
gedit ../Samples/new/new/DX9/VertexTextureFetchWater/Viewer.cpp&
gedit ../Samples/new/new/DX9/HDRCubeMap/HDRCubeMap.cpp&
gedit ../Samples/new/new/DX11/Hair/SimpleRT.h&
gedit ../Samples/new/new/DX11/Hair/HairShadows.h&
gedit ../Samples/new/new/DX11/Hair/Fluid.cpp&
gedit ../Samples/new/new/DX11/Hair/grid.h&
gedit ../Samples/new/new/DX11/Hair/LoadHairFile.cpp&
gedit ../Samples/new/new/DX11/Hair/DensityGrid.h&
gedit ../Samples/new/new/DX11/Hair/Common.cpp&
gedit ../Samples/new/new/DX11/Hair/Fluid.h&
gedit ../Samples/new/new/DX11/Hair/Hair.h&
gedit ../Samples/new/new/DX11/Hair/resource.h&
gedit ../Samples/new/new/DX11/Hair/Grid.cpp&
gedit ../Samples/new/new/DX11/Hair/DensityGrid.cpp&
gedit ../Samples/new/new_/DX/DeferredParticles/BreakableWall.h&
gedit ../Samples/new/new_/DX/DeferredParticles/BreakableWall.cpp&
gedit ../Samples/new/new_/DX/DeferredParticles/ParticleSystem.cpp&
gedit ../Samples/new/new_/DX/DeferredParticles/ParticleSystem.h&
gedit ../Samples/new/new_/DX/DeferredParticles/DeferredParticles.cpp&
gedit ../Samples/new/new_/DX/RaycastTerrain/Terrain.h&
gedit ../Samples/new/new_/DX/RaycastTerrain/Terrain.cpp&
gedit ../Samples/new/new_/DX/RaycastTerrain/RaycastTerrain.cpp&
gedit ../Samples/new/new_/DX/Skinning10/Skinning10.cpp&
gedit ../Samples/new/new_/DX/PerlinFire/PerlinFire.cpp&
gedit ../Samples/new/new_/DX/ParallaxOcclusionMapping/ParallaxOcclusionMapping.cpp&
gedit ../Samples/new/new_/DX/HDR/App.cpp&
gedit ../Samples/new/new_/DX/Rain/Rain.cpp&
gedit ../Samples/new/new_/DX/Island11/terrain.cpp&
gedit ../Samples/new/new_/DX/Island11/Island11.cpp&
gedit ../Samples/new/new_/DX/Island11/terrain.h&
gedit ../Samples/new/new_/DX/Island11/Island11.h&
gedit ../Samples/new/new_/DX/TerrainTessellation/Stars.h&
gedit ../Samples/new/new_/DX/TerrainTessellation/Stars.cpp&
gedit ../Samples/new/new_/DX/TerrainTessellation/TileRing.cpp&
gedit ../Samples/new/new_/DX/TerrainTessellation/TileRing.h&
gedit ../Samples/new/new_/DX/TerrainTessellation/TerrainTessellation.cpp&
gedit ../Samples/new/new_/DX/SnowAccumulation/SnowAccumulation.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/PackedFile.h&
gedit ../Samples/new/new_/DX/ContentStreaming/ResourceReuseCache.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/Terrain.h&
gedit ../Samples/new/new_/DX/ContentStreaming/PackedFile.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/AsyncLoader.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/ContentStreaming9.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/ContentLoaders.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/ResourceReuseCache.h&
gedit ../Samples/new/new_/DX/ContentStreaming/Terrain.cpp&
gedit ../Samples/new/new_/DX/ContentStreaming/ContentLoaders.h&
gedit ../Samples/new/new_/DX/ContentStreaming/AsyncLoader.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Footprint/SnowSystem.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Footprint/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Footprint/SnowSystem.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-IK/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/18/CRenderer.cpp&
gedit ../Samples/new/new_/R2VB_VTF/18/main.cpp&
gedit ../Samples/new/new_/R2VB_VTF/Skinning10/Skinning10.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Sort/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-ShadowVolume/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-NPatches/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Collision/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/physics.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/GPUPhysics.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/fftw3.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/CPUphysics.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/CPUphysics.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/common.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/physics.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/FFT.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/GPUphysics.h&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-OceanWater/r2vb.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-TerrainMorph/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Animation/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Cloth/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-ParticleSystem/App.cpp&
gedit ../Samples/new/new_/R2VB_VTF/R2VB-Water/App.cpp

