import os, sys, re, math
from PIL import Image
from os import listdir
from os.path import isfile, join
import fnmatch
import shutil
import ftplib

def osmakedirs(fn):
	if not os.path.exists(fn):
		#print 'osmakedirs(%s)' % (fn)
		os.makedirs(fn)

files='''./ModernMisc/+Image38.jpg
./ModernMisc/misslies.jpg
./Warships/pont.BMP
./Warships/Coque.bmp
./Warships/ecran.bmp
./Warships/fleet.jpg
./Warships/EicheV.jpg
./Warships/wakefa.bmp
./Warships/frigate1_0032.jpg
./Warships/Beschlag.jpg
./Warships/BUCHENAT.jpg
./Warships/pod.bmp
./Warships/corvette0032.jpg
./Warships/helico.bmp
./Warships/Emblem.jpg
./Warships/elster.jpg
./Warships/Riffel2.jpg
./Warships/console.bmp
./Warships/kompass.jpg
./Warships/moquette.bmp
./Warships/fleetth.jpg
./Warships/Super.bmp
./Warships/fond1.bmp
./Warships/EICHE.jpg
./Warships/MaschTel.jpg
./Warships/cuir.bmp
./Warships/+Image45.jpg
./Warships/warships1.jpg
./Warships/elste1.jpg
./Warships/Chain_a.bmp
./Warships/pilot.bmp
./Warships/seat.bmp
./Warships/frigate2_0032.jpg
./P-WarplaneHistory/p-51/TexturesZATOKA.png
./P-WarplaneHistory/p-51/Textures51_OP.png
./P-WarplaneHistory/p-51/Textures51_kadL.png
./P-WarplaneHistory/p-51/TexturesSKY1.png
./P-WarplaneHistory/p-51/Textures51_kadP.png
./P-WarplaneHistory/p-51/Textures51_OLDSK.png
./P-WarplaneHistory/p-51/Textures51_winBB.png
./P-WarplaneHistory/p-51/Textures51_winB.png
./P-WarplaneHistory/p-51/Textures51_winT.png
./P-WarplaneHistory/p-51/Textures51_FELGI.png
./P-WarplaneHistory/p-51/Textures51_winT2.png
./P-WarplaneHistory/p-51/TexturesLeather.png
./P-WarplaneHistory/p-51/Textures51_CHROM.png
./P-WarplaneHistory/p-51/Textures51_winB2.png
./P-WarplaneHistory/p-51/Textures51_FELG.png
./P-WarplaneHistory/p-51/Textures51_STAT.png
./P-WarplaneHistory/p-51/Textures51_lotb.png
./P-WarplaneHistory/p-51/Textures51_kadLB.png
./P-WarplaneHistory/p-51/TexturesALUMO1.png
./P-WarplaneHistory/p-51/Textures51_PW.png
./P-WarplaneHistory/p-51/Textures51_TAB.png
./P-WarplaneHistory/p-51/Textures51_winTB.png
./P-WarplaneHistory/p-51/Textures51_statB.png
./P-WarplaneHistory/Mc202/TexturesMC_kadTB.png
./P-WarplaneHistory/Mc202/TexturesMC_Leath.png
./P-WarplaneHistory/Mc202/TexturesMC_kad_L.png
./P-WarplaneHistory/Mc202/TexturesMC_pok_Z.png
./P-WarplaneHistory/Mc202/TexturesMC_wrag.png
./P-WarplaneHistory/Mc202/TexturesSKY1.png
./P-WarplaneHistory/Mc202/TexturesMC_kolpB.png
./P-WarplaneHistory/Mc202/TexturesMC_wg_b.png
./P-WarplaneHistory/Mc202/TexturesMC_Lop.png
./P-WarplaneHistory/Mc202/TexturesMC_cool.png
./P-WarplaneHistory/Mc202/TexturesMC_pok_W.png
./P-WarplaneHistory/Mc202/TexturesMC_kadT.png
./P-WarplaneHistory/Mc202/TexturesMC_kad_P.png
./P-WarplaneHistory/Mc202/TexturesMC_oldsk.png
./P-WarplaneHistory/Mc202/TexturesMC_pokZB.png
./P-WarplaneHistory/Mc202/TexturesMC_tab.png
./P-WarplaneHistory/Mc202/TexturesMC_wg_bb.png
./P-WarplaneHistory/Mc202/TexturesMETAL.png
./P-WarplaneHistory/Mc202/TexturesMC_wg_t.png
./P-WarplaneHistory/Mc202/TexturesMC_st_B.png
./P-WarplaneHistory/Mc202/TexturesMc202_tab.png
./P-WarplaneHistory/Mc202/TexturesMC_st_T.png
./P-WarplaneHistory/Mc202/TexturesMC_st_BB.png
./P-WarplaneHistory/Mc202/TexturesMC_kadb.png
./P-WarplaneHistory/Mc202/TexturesMC_op_B.png
./P-WarplaneHistory/Mc202/TexturesCHRM.png
./P-WarplaneHistory/Mc202/TexturesMC_wg_tb.png
./P-WarplaneHistory/Mc202/TexturesMC_kolp.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_wingT.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_wgTB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesZATOKA.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stpoB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesSKY1.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_wingB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_lop.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_tab.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVB_kadP.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_op_b.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_100oo.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVB_kadLB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stpL.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVB_kadPB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_kadL.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesCeme.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_100oc.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stp_B.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stpiB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stpoT.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_wgBB.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_leath.png
./P-WarplaneHistory/Spit_Vb/Spitfire_Vb/TexturesVb_stpP.png
./P-WarplaneHistory/Fw190D/TexturesFW_TAB.png
./P-WarplaneHistory/Fw190D/TexturesD9_LotkL.png
./P-WarplaneHistory/Fw190D/TexturesD9_Plate.png
./P-WarplaneHistory/Fw190D/TexturesD9_pok_w.png
./P-WarplaneHistory/Fw190D/TexturesD9_kadLB.png
./P-WarplaneHistory/Fw190D/TexturesD9_stpob.png
./P-WarplaneHistory/Fw190D/TexturesD9_kadPB.png
./P-WarplaneHistory/Fw190D/TexturesD9_statP.png
./P-WarplaneHistory/Fw190D/TexturesSKY1.png
./P-WarplaneHistory/Fw190D/TexturesD9_METAL.png
./P-WarplaneHistory/Fw190D/TexturesD9_KAB.png
./P-WarplaneHistory/Fw190D/TexturesD9_cool.png
./P-WarplaneHistory/Fw190D/TexturesD9_stpoT.png
./P-WarplaneHistory/Fw190D/TexturesD9_winBB.png
./P-WarplaneHistory/Fw190D/TexturesD9_kadL.png
./P-WarplaneHistory/Fw190D/TexturesD9_winTB.png
./P-WarplaneHistory/Fw190D/TexturesD9_lotbl.png
./P-WarplaneHistory/Fw190D/TexturesD9_staPB.png
./P-WarplaneHistory/Fw190D/TexturesD9_wingB.png
./P-WarplaneHistory/Fw190D/TexturesD9_lotsp.png
./P-WarplaneHistory/Fw190D/TexturesD9_leath.png
./P-WarplaneHistory/Fw190D/TexturesD9_wingT.png
./P-WarplaneHistory/Fw190D/TexturesD9_kadP.png
./P-WarplaneHistory/Fw190D/TexturesD9_LotkB.png
./P-WarplaneHistory/Fw190D/TexturesD9_pok_Z.png
./AncientSmallarms/warmace5_0032.jpg
./AncientSmallarms/helb2_0032.jpg
./AncientSmallarms/warhammer8_0032.jpg
./AncientSmallarms/pike1_0032.jpg
./AncientSmallarms/warhammer6_0032.jpg
./AncientSmallarms/warfork3_0032.jpg
./AncientSmallarms/helmbe1_0032.jpg
./AncientSmallarms/gllefe_che0032.jpg
./AncientSmallarms/sarissa0032.jpg
./AncientSmallarms/glefe3_0032.jpg
./AncientSmallarms/bh14jhe0032.jpg
./AncientSmallarms/club0032.jpg
./AncientSmallarms/warhammer2_0032.jpg
./AncientSmallarms/pike4_0032.jpg
./AncientSmallarms/warhammer5_0032.jpg
./AncientSmallarms/warax1_0032.jpg
./AncientSmallarms/esword0032.jpg
./AncientSmallarms/warhammer4_0032.jpg
./AncientSmallarms/helmbe2_0032.jpg
./AncientSmallarms/+Image33.jpg
./AncientSmallarms/warmace1_0032.jpg
./AncientSmallarms/glefe2_0032.jpg
./AncientSmallarms/warhammer3_0032.jpg
./AncientSmallarms/kmuskets0032.jpg
./AncientSmallarms/rapier0032.jpg
./AncientSmallarms/helb1_0032.jpg
./AncientSmallarms/+Image31.jpg
./AncientSmallarms/elance0032.jpg
./AncientSmallarms/weststuff0032.jpg
./AncientSmallarms/barbsw0032.jpg
./AncientSmallarms/warax4_0032.jpg
./AncientSmallarms/warmace2_0032.jpg
./AncientSmallarms/warfork1_0032.jpg
./AncientSmallarms/pike3_0032.jpg
./AncientSmallarms/pike5_0032.jpg
./AncientSmallarms/warmace3_0032.jpg
./AncientSmallarms/glefe_2_0032.jpg
./AncientSmallarms/12Jh2_0032.jpg
./AncientSmallarms/katana0032.jpg
./AncientSmallarms/flamberge0032.jpg
./AncientSmallarms/helmbe3_0032.jpg
./AncientSmallarms/warhammer1_0032.jpg
./AncientSmallarms/warfork2_0032.jpg
./AncientSmallarms/warax2_0032.jpg
./AncientSmallarms/gladius0032.jpg
./AncientSmallarms/+Image34.jpg
./AncientSmallarms/+Image32.jpg
./AncientSmallarms/pila0032.jpg
./AncientSmallarms/warmace43_0032.jpg
./AncientSmallarms/warhammer7_0032.jpg
./AncientSmallarms/sabre0032.jpg
./AncientSmallarms/helmb1_0032.jpg
./AncientSmallarms/scimitar0032.jpg
./AncientSmallarms/bowz0032.jpg
./AncientSmallarms/helmb3_0032.jpg
./AncientSmallarms/pike2_0032.jpg
./AncientSmallarms/warax3_0032.jpg
./Aircraft/Pfeil2.jpg
./Aircraft/Seite.jpg
./Aircraft/dauru.jpg
./Aircraft/btiles.jpg
./Aircraft/Spinner.jpg
./Aircraft/rumpfL.jpg
./Aircraft/Kreuz.jpg
./Aircraft/turbo2.jpg
./Aircraft/rs1.jpg
./Aircraft/a10.jpg
./Aircraft/sabengm.jpg
./Aircraft/wcwLu.jpg
./Aircraft/wcsR.jpg
./Aircraft/heckf.jpg
./Aircraft/+Image42.jpg
./Aircraft/m262.jpg
./Aircraft/KreuzWs.jpg
./Aircraft/sabsb.jpg
./Aircraft/sabplt.jpg
./Aircraft/m262inst.jpg
./Aircraft/sabmain.jpg
./Aircraft/TragFL.jpg
./Aircraft/TragFR.jpg
./Aircraft/dwingbot.jpg
./Aircraft/klappe.jpg
./Aircraft/stuka.jpg
./Aircraft/refmapsky.jpg
./Aircraft/Lakerem.jpg
./Aircraft/sabwlb.jpg
./Aircraft/m23.jpg
./Aircraft/ls1.jpg
./Aircraft/ju87.jpg
./Aircraft/daunrf.jpg
./Aircraft/wcsL.jpg
./Aircraft/wcwRu.jpg
./Aircraft/sabs.jpg
./Aircraft/tragfu.jpg
./Aircraft/Strich.jpg
./Aircraft/rumpfRe.jpg
./Aircraft/KreuzH.jpg
./Aircraft/leitw3.jpg
./Aircraft/wcLt.jpg
./Aircraft/DUSKCLD1.JPG
./Aircraft/sabintd.jpg
./Aircraft/+Image43.jpg
./Aircraft/heckf1.jpg
./Aircraft/sabrewr.jpg
./Aircraft/dwingtop.jpg
./Aircraft/109rc.jpg
./Aircraft/wcRt.jpg
./Aircraft/sabrewrb.jpg
./Aircraft/sabwi.jpg
./Aircraft/sabmainb.jpg
./Aircraft/Beschr.jpg
./Aircraft/heck.jpg
./Aircraft/Kreis.jpg
./Aircraft/blackh.jpg
./Aircraft/ls4.jpg
./Aircraft/sabwhe.jpg
./Aircraft/sabwha.jpg
./Aircraft/fluu1.jpg
./Aircraft/sabint.jpg
./Aircraft/sabwl.jpg
./Aircraft/ju87t.jpg
./Aircraft/leitw2.jpg
./Aircraft/bwingtop.jpg
./Aircraft/dauntlf.jpg
./Aircraft/Zylinder.jpg
./Aircraft/109rb.jpg
./Aircraft/tragflL3.jpg
./Aircraft/sabeng.jpg
./Aircraft/Streifen.jpg
./Aircraft/Rumpf.jpg
./Aircraft/Side.jpg
./Aircraft/HLeitw.jpg
./ModernSmallarms/pzfst0032.jpg
./ModernSmallarms/prueba_t.jpg
./ModernSmallarms/m16_0032.jpg
./ModernSmallarms/stgren0032.jpg
./ModernSmallarms/smg0032.jpg
./ModernSmallarms/garand0032.jpg
./ModernSmallarms/mg3_0032.jpg
./ModernSmallarms/stg.jpg
./ModernSmallarms/mpis.jpg
./ModernSmallarms/mp5_0032.jpg
./ModernSmallarms/mg3.jpg
./ModernSmallarms/sponge.jpg
./ModernSmallarms/+Image39.jpg
./ModernSmallarms/m82.jpg
./ModernSmallarms/bayo0032.jpg
./ModernSmallarms/sschm.jpg
./ModernSmallarms/uzi0032.jpg
./ModernSmallarms/sand2.jpg
./ModernSmallarms/bazoo0032.jpg
./ModernSmallarms/glock0032.jpg
./ModernSmallarms/misc.jpg
./ModernSmallarms/pushka.jpg
./ModernSmallarms/shotg1.jpg
./ModernSmallarms/rem0032.jpg
./ModernSmallarms/garand.jpg
./ModernSmallarms/tg.jpg
./ModernSmallarms/sand.jpg
./ModernSmallarms/pushka0032.jpg
./ModernSmallarms/thomps0032.jpg
./ModernSmallarms/+Image40.jpg
./ModernSmallarms/fn0032.jpg
./ModernSmallarms/water2.jpg
./ModernSmallarms/WS_FTP.LOG
./ModernSmallarms/smg.jpg
./ModernSmallarms/sw44_0032.jpg
./ModernSmallarms/ss.jpg
./ModernSmallarms/fn.jpg
./ModernSmallarms/jack0032.jpg
./ModernSmallarms/m82_0032.jpg
./ModernSmallarms/sw44.jpg
./ModernSmallarms/silent0032.jpg
./ModernSmallarms/stg0032.jpg
./ModernSmallarms/schme0032.jpg
./ModernSmallarms/3g.jpg
./ModernSmallarms/oak.jpg
./ModernSmallarms/m16.jpg
./ModernSmallarms/mahogany.jpg
./ModernSmallarms/ashsen_2.jpg
./AncientArmour/efishscale0032.jpg
./AncientArmour/morion0032.jpg
./AncientArmour/greekarm0032.jpg
./AncientArmour/greekshield0032.jpg
./AncientArmour/helrom0032.jpg
./AncientArmour/lorica0032.jpg
./AncientArmour/helviki0032.jpg
./AncientArmour/+Image26.jpg
./AncientArmour/helmek0032.jpg
./AncientArmour/chmail0032.jpg
./AncientArmour/amazharn0032.jpg
./AncientArmour/helmegr0032.jpg
./AncientArmour/heltin0032.jpg
./AncientArmour/ironclad0032.jpg
./AncientArmour/bharn0032.jpg
./AncientArmour/+Image27.jpg
./AncientArmour/egarmor0032.jpg
./AncientArmour/ebuckler0032.jpg
./AncientArmour/helmeg0032.jpg
./screenshots PlanetMilitaryPRO.html
./AncientMisc/+ancient_misc1.jpg
./P-TankHistory/german/TigerWittmannmg_msk_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_f2_b.png
./P-TankHistory/german/TigerWittmanntrt_bk_d.TIF.png
./P-TankHistory/german/TigerWittmannidle_b.png
./P-TankHistory/german/TigerWittmannex_pip_b.TIF.png
./P-TankHistory/german/TigerWittmanntrt_bk_b.png
./P-TankHistory/german/TigerWittmannro_whl_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_b_b.TIF.png
./P-TankHistory/german/TigerWittmanndr_ht1_d.png
./P-TankHistory/german/TigerWittmannw_b_w.png
./P-TankHistory/german/TigerWittmannmgd_b_d.TIF.png
./P-TankHistory/german/TigerWittmannvis_l_d.TIF.png
./P-TankHistory/german/TigerWittmannTrck_s_b.png
./P-TankHistory/german/TigerWittmannesc_ht_d.TIF.png
./P-TankHistory/german/TigerWittmanndr_whl_b.TIF.png
./P-TankHistory/german/TigerWittmannTrck_t_d.tif.png
./P-TankHistory/german/TigerWittmannmg_msk_d.TIF.png
./P-TankHistory/german/TigerWittmanntls_bx_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_ms2_d.png
./P-TankHistory/german/TigerWittmannmg_sid_d.TIF.png
./P-TankHistory/german/TigerWittmannexhst_b.png
./P-TankHistory/german/TigerWittmanntrt_rt_d.TIF.png
./P-TankHistory/german/TigerWittmanncmtu_t_d.TIF.png
./P-TankHistory/german/TigerWittmannmgd_f3_b.png
./P-TankHistory/german/TigerWittmanntrt_lt_b.TIF.png
./P-TankHistory/german/TigerWittmanndr_ht1_d.TIF.png
./P-TankHistory/german/TigerWittmanntrt_bk_d.png
./P-TankHistory/german/TigerWittmanngn_ms1_d.TIF.png
./P-TankHistory/german/TigerWittmannmgd_f2_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_msk_d.TIF.png
./P-TankHistory/german/TigerWittmannvis_r_d.png
./P-TankHistory/german/TigerWittmannmgd_f2_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_f3_d.png
./P-TankHistory/german/TigerWittmannw_b_w1.TIF.png
./P-TankHistory/german/TigerWittmanngn_ms1_b.png
./P-TankHistory/german/TigerWittmannmgd_f3_d.TIF.png
./P-TankHistory/german/TigerWittmannesc_ht_d.png
./P-TankHistory/german/TigerWittmannTrack_d.png
./P-TankHistory/german/TigerWittmannex_pip_b.png
./P-TankHistory/german/TigerWittmannmgd_f2_d.png
./P-TankHistory/german/TigerWittmanntrt_tp_b.png
./P-TankHistory/german/TigerWittmannTrck_s_o.png
./P-TankHistory/german/TigerWittmannTrck_s_d.tif.png
./P-TankHistory/german/TigerWittmanncimerit.png
./P-TankHistory/german/TigerWittmannmgd_f1_d.png
./P-TankHistory/german/TigerWittmannvis_r_d.TIF.png
./P-TankHistory/german/TigerWittmanntrt_tp_d.TIF.png
./P-TankHistory/german/TigerWittmanntrt_lt_d.TIF.png
./P-TankHistory/german/TigerWittmannTrck_s_d.png
./P-TankHistory/german/TigerWittmannexhst_d.TIF.png
./P-TankHistory/german/TigerWittmannro_whl_d.TIF.png
./P-TankHistory/german/TigerWittmannro_whl_d.png
./P-TankHistory/german/TigerWittmannmgd_s_d.png
./P-TankHistory/german/TigerWittmannfan_cv_d.png
./P-TankHistory/german/TigerWittmannTrack_sh.png
./P-TankHistory/german/TigerWittmanndr_whl_b.png
./P-TankHistory/german/TigerWittmanngn_msk_b.png
./P-TankHistory/german/TigerWittmannfan_cv_d.TIF.png
./P-TankHistory/german/TigerWittmannmg_msk_b.png
./P-TankHistory/german/TigerWittmanndr_htc_d.png
./P-TankHistory/german/TigerWittmanntrt_tp_b.TIF.png
./P-TankHistory/german/TigerWittmannTrack_sh.tif.png
./P-TankHistory/german/TigerWittmannbod_f2_b.png
./P-TankHistory/german/TigerWittmannring_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_msk_b.TIF.png
./P-TankHistory/german/TigerWittmanntrt_rt_d.png
./P-TankHistory/german/TigerWittmannmgd_b_d.png
./P-TankHistory/german/TigerWittmanncv_eng_b.png
./P-TankHistory/german/TigerWittmannmgd_s4_d.TIF.png
./P-TankHistory/german/TigerWittmannbody_b_d.png
./P-TankHistory/german/TigerWittmannTrack_b.png
./P-TankHistory/german/TigerWittmanncimerit.TIF.png
./P-TankHistory/german/TigerWittmannldr_t_b.TIF.png
./P-TankHistory/german/TigerWittmannldr_t_d.png
./P-TankHistory/german/TigerWittmannfn_cvr_d.TIF.png
./P-TankHistory/german/TigerWittmannmgd_s2_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_ms1_b.TIF.png
./P-TankHistory/german/TigerWittmannair_in_b.TIF.png
./P-TankHistory/german/TigerWittmannro_whl_b.png
./P-TankHistory/german/TigerWittmannmgd_f4_d.png
./P-TankHistory/german/TigerWittmannidle_b.TIF.png
./P-TankHistory/german/TigerWittmanndr_msk_d.png
./P-TankHistory/german/TigerWittmannmgd_s3_d.png
./P-TankHistory/german/TigerWittmannmgd_s3_d.TIF.png
./P-TankHistory/german/TigerWittmannTrck_t_d.png
./P-TankHistory/german/TigerWittmannvis_l_d.png
./P-TankHistory/german/TigerWittmanntrt_lt_b.png
./P-TankHistory/german/TigerWittmannpst_pt_d.TIF.png
./P-TankHistory/german/TigerWittmannldr_t_b.png
./P-TankHistory/german/TigerWittmanncv_eng_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_ms2_d.TIF.png
./P-TankHistory/german/TigerWittmannbarrel_d.TIF.png
./P-TankHistory/german/TigerWittmannmg_sid_d.png
./P-TankHistory/german/TigerWittmannmgd_f4_d.TIF.png
./P-TankHistory/german/TigerWittmann/ex_pip_b.TIF
./P-TankHistory/german/TigerWittmann/trt_tp_d.TIF
./P-TankHistory/german/TigerWittmann/Ashsen.jpg
./P-TankHistory/german/TigerWittmann/gn_ms2_d.TIF
./P-TankHistory/german/TigerWittmann/gn_msk_d.TIF
./P-TankHistory/german/TigerWittmann/TRACK1_B.JPG
./P-TankHistory/german/TigerWittmann/dr_ht1_d.TIF
./P-TankHistory/german/TigerWittmann/cv_eng_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_s_b.TIF
./P-TankHistory/german/TigerWittmann/mgd_s_d.TIF
./P-TankHistory/german/TigerWittmann/exhst_b.TIF
./P-TankHistory/german/TigerWittmann/dr_htc_d.TIF
./P-TankHistory/german/TigerWittmann/t1naked.jpg
./P-TankHistory/german/TigerWittmann/body_b_d.TIF
./P-TankHistory/german/TigerWittmann/BOD_F3_D.jpg
./P-TankHistory/german/TigerWittmann/Track_sh.tif
./P-TankHistory/german/TigerWittmann/trt_lt_d.TIF
./P-TankHistory/german/TigerWittmann/mg_sid_d.TIF
./P-TankHistory/german/TigerWittmann/gn_ms1_b.TIF
./P-TankHistory/german/TigerWittmann/ro_whl_b.TIF
./P-TankHistory/german/TigerWittmann/mgd_f3_d.TIF
./P-TankHistory/german/TigerWittmann/esc_ht_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_f4_d.TIF
./P-TankHistory/german/TigerWittmann/ldr_t_b.TIF
./P-TankHistory/german/TigerWittmann/cimerit.TIF
./P-TankHistory/german/TigerWittmann/barrel_d.TIF
./P-TankHistory/german/TigerWittmann/Trck_s_o.tif
./P-TankHistory/german/TigerWittmann/ro_whl_d.TIF
./P-TankHistory/german/TigerWittmann/cmtu_t_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_s2_d.TIF
./P-TankHistory/german/TigerWittmann/t2naked.jpg
./P-TankHistory/german/TigerWittmann/trt_lt_b.TIF
./P-TankHistory/german/TigerWittmann/t1.jpg
./P-TankHistory/german/TigerWittmann/vis_r_d.TIF
./P-TankHistory/german/TigerWittmann/Trck_s_b.tif
./P-TankHistory/german/TigerWittmann/cv_eng_b.TIF
./P-TankHistory/german/TigerWittmann/Trck_t_d.tif
./P-TankHistory/german/TigerWittmann/mg_msk_b.TIF
./P-TankHistory/german/TigerWittmann/trt_rt_d.TIF
./P-TankHistory/german/TigerWittmann/bod_f2_b.TIF
./P-TankHistory/german/TigerWittmann/dr_msk_d.TIF
./P-TankHistory/german/TigerWittmann/BOD_F2_D.jpg
./P-TankHistory/german/TigerWittmann/gn_ms1_d.TIF
./P-TankHistory/german/TigerWittmann/fn_cvr_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_f3_b.TIF
./P-TankHistory/german/TigerWittmann/ring_d.TIF
./P-TankHistory/german/TigerWittmann/gn_msk_b.TIF
./P-TankHistory/german/TigerWittmann/gn_ms3_d.TIF
./P-TankHistory/german/TigerWittmann/trt_bk_b.TIF
./P-TankHistory/german/TigerWittmann/t2.jpg
./P-TankHistory/german/TigerWittmann/dr_whl_b.TIF
./P-TankHistory/german/TigerWittmann/mgd_s3_d.TIF
./P-TankHistory/german/TigerWittmann/BOD_F1_D.jpg
./P-TankHistory/german/TigerWittmann/mgd_f2_d.TIF
./P-TankHistory/german/TigerWittmann/idle_b.TIF
./P-TankHistory/german/TigerWittmann/air_in_b.TIF
./P-TankHistory/german/TigerWittmann/mg_msk_d.TIF
./P-TankHistory/german/TigerWittmann/w_b_w1.TIF
./P-TankHistory/german/TigerWittmann/ldr_t_d.TIF
./P-TankHistory/german/TigerWittmann/Track_b.tif
./P-TankHistory/german/TigerWittmann/Track_d.tif
./P-TankHistory/german/TigerWittmann/trt_bk_d.TIF
./P-TankHistory/german/TigerWittmann/tls_bx_d.TIF
./P-TankHistory/german/TigerWittmann/vis_l_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_f1_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_b_b.TIF
./P-TankHistory/german/TigerWittmann/Trck_s_d.tif
./P-TankHistory/german/TigerWittmann/exhst_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_s4_d.TIF
./P-TankHistory/german/TigerWittmann/pst_pt_d.TIF
./P-TankHistory/german/TigerWittmann/glass.tif
./P-TankHistory/german/TigerWittmann/trt_tp_b.TIF
./P-TankHistory/german/TigerWittmann/mgd_b_d.TIF
./P-TankHistory/german/TigerWittmann/mgd_f2_b.TIF
./P-TankHistory/german/TigerWittmann/fan_cv_d.TIF
./P-TankHistory/german/TigerWittmann/w_b_w.TIF
./P-TankHistory/german/TigerWittmanngn_msk_d.png
./P-TankHistory/german/TigerWittmanntrt_tp_d.png
./P-TankHistory/german/TigerWittmannbody_b_d.TIF.png
./P-TankHistory/german/TigerWittmanngn_ms3_d.png
./P-TankHistory/german/TigerWittmannexhst_b.TIF.png
./P-TankHistory/german/TigerWittmannw_b_w.TIF.png
./P-TankHistory/german/TigerWittmannmgd_s_b.png
./P-TankHistory/german/TigerWittmannpst_pt_d.png
./P-TankHistory/german/TigerWittmannmgd_b_b.png
./P-TankHistory/german/TigerWittmannring_d.png
./P-TankHistory/german/TigerWittmannTrack_d.tif.png
./P-TankHistory/german/TigerWittmanncv_eng_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_s_d.TIF.png
./P-TankHistory/german/TigerWittmannexhst_d.png
./P-TankHistory/german/TigerWittmannmg_msk_d.png
./P-TankHistory/german/TigerWittmanncmtu_t_d.png
./P-TankHistory/german/TigerWittmannmgd_s_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_s2_d.png
./P-TankHistory/german/TigerWittmanngn_ms3_d.TIF.png
./P-TankHistory/german/TigerWittmannTrck_s_b.tif.png
./P-TankHistory/german/TigerWittmannfn_cvr_d.png
./P-TankHistory/german/TigerWittmannTrck_s_o.tif.png
./P-TankHistory/german/TigerWittmannbarrel_d.png
./P-TankHistory/german/TigerWittmanngn_ms1_d.png
./P-TankHistory/german/TigerWittmanntls_bx_d.png
./P-TankHistory/german/TigerWittmanntrt_bk_b.TIF.png
./P-TankHistory/german/TigerWittmannw_b_w1.png
./P-TankHistory/german/TigerWittmanntrt_lt_d.png
./P-TankHistory/german/TigerWittmannmgd_f3_b.TIF.png
./P-TankHistory/german/TigerWittmannldr_t_d.TIF.png
./P-TankHistory/german/TigerWittmannglass.tif.png
./P-TankHistory/german/TigerWittmanndr_msk_d.TIF.png
./P-TankHistory/german/TigerWittmanncv_eng_d.png
./P-TankHistory/german/TigerWittmannbod_f2_b.TIF.png
./P-TankHistory/german/TigerWittmannmgd_s4_d.png
./P-TankHistory/german/TigerWittmanndr_htc_d.TIF.png
./P-TankHistory/german/TigerWittmannmgd_f1_d.TIF.png
./P-TankHistory/german/TigerWittmannair_in_b.png
./P-TankHistory/german/TigerWittmannTrack_b.tif.png
./P-TankHistory/german/TigerWittmannglass.png
./run.py
./Characters/waffenSS.jpg
./Characters/nmarinedigit.jpg
./Characters/UPARM.jpg
./Characters/BODYUP.jpg
./Characters/desertcamo.jpg
./Characters/+p-typ2f-inf-a.bmp
./Characters/gladiator.jpg
./Characters/chainmail2.jpg
./Characters/+p-typ2f-inf-b.bmp
./Characters/hoplite.jpg
./Characters/tunica2.jpg
./Characters/helmetGI.jpg
./Characters/Abdomen.jpg
./Characters/Loleg.jpg
./Characters/sycamo1.jpg
./Characters/+Image36.jpg
./Characters/LOARM.jpg
./Characters/fishscale3.jpg
./Characters/repGuard2.jpg
./Characters/chainmail1.jpg
./Characters/+Image35.jpg
./Characters/descorp.jpg
./Characters/rgcamo.jpg
./Characters/WS_FTP.LOG
./Characters/Fell2.jpg
./Characters/Mil.jpg
./Characters/fishscale2.jpg
./Characters/scutum.jpg
./Characters/tunica.jpg
./Characters/+Image37.jpg
./Characters/fishscale1.jpg
./Characters/Fell3.jpg
./Characters/largedesert.jpg
./Characters/Upleg.jpg
./Characters/stoned6.jpg
./Characters/glad4.jpg
./AncientArtillery/+Image28.jpg
./Vehicles/th.jpg
./Vehicles/t722b.jpg
./Vehicles/t-72tile.jpg
./Vehicles/t72tur.jpg
./Vehicles/+Image2.jpg
./Vehicles/+Image1.jpg
./Vehicles/+Image4.jpg
./Vehicles/t72gun.jpg
./Vehicles/ght.jpg
./Vehicles/lag.jpg
./Vehicles/t72_0055.jpg
./Vehicles/+Image3.jpg
./Vehicles/Mil.jpg
./Vehicles/Military.jpg
./Vehicles/leotile1.jpg
./Vehicles/+Image6.jpg
./Vehicles/Military2.jpg
'''

def whtml(files, name, d):
	f=open('./screenshots '+name+'.html','w')
	ln='<HTML>\n<HEAD>\n</HEAD>\n<BODY>\n<TITLE>Screenshots '+name+'</TITLE>\n<H1>Screenshots '+name+'</H1>\n<TABLE>\n'
	f.write(ln)
	for y in range(0,d+1):
		ln='<TR>'
		for x in range(0,d+1):
			ln_='<TD></TD>'
			if (d*y+x)<len(files):
				f_=files[d*y+x]
				f__=f_

				head, tail = os.path.split(f_)
				name, ext = os.path.splitext(tail)
				#print ext
				#exit(0)
				if ext in ['.tif','.TIF','.tga','.TGA']:
					f__=head+name+'.png'

				if ext=='.tif':
					#f__=f__.replace('.tif', '')
					os.system('convert '+f_+' '+f__)
				if ext=='.TIF':
					#f__=f__.replace('.TIF', '')
					os.system('convert '+f_+' '+f__)
				if ext=='.tga':
					#f__=f__.replace('.tga', '')
					os.system('convert '+f_+' '+f__)
				if ext=='.TGA':
					#f__=f__.replace('.TGA', '')
					os.system('convert '+f_+' '+f__)
				
				#f_=f_.replace('../../public_html/screenshots256x256/','./')
				ln_='<TD><img src="%s" alt="Screenshot(%s)"></TD>' % (f__,f__)
			ln+=ln_
		f.write(ln+'</TR>\n')
	#f_='./tiny.jpg
	#ln='<TR><TD><img src="%s" alt="Screenshot(%s)"></TD></TR>\n' % (f_,f_)
	#f.write(ln)
	ln='</TABLE>\n</BODY>\n</HTML>\n'
	f.write(ln)
	f.close()

files=files.replace('./','./')
v=files.split('\n')
#for i in v:
#	print i
whtml(v, 'PlanetMilitaryPRO', 23)

