./samples/gles2_book/Common/Win32/esUtil_TGA.c
./samples/gles2_book/Common/Win32/esUtil_win32.c
./samples/gles2_book/Common/esUtil.c
./samples/gles2_book/Common/esShader.c
./samples/gles2_book/Common/esShapes.c
./samples/gles2_book/Common/esTransform.c

TextureWrap:

SRCS =     ./samples/gles2_book/TextureWrap/TextureWrap.c
MultiTexture:

SRCS =     ./samples/gles2_book/MultiTexture/MultiTexture.c
PostSubBuffer:

SRCS =     ./samples/gles2_book/PostSubBuffer/PostSubBuffer.c
MipMap2D:

SRCS =     ./samples/gles2_book/MipMap2D/MipMap2D.c
Hello_Triangle:

SRCS =     ./samples/gles2_book/Hello_Triangle/Hello_Triangle.c
ParticleSystem:

SRCS =     ./samples/gles2_book/ParticleSystem/ParticleSystem.c
Simple_VertexShader:

SRCS =     ./samples/gles2_book/Simple_VertexShader/Simple_VertexShader.c
MultipleRenderTargets:

SRCS =     ./samples/gles2_book/MultipleRenderTargets/MultipleRenderTargets.c
Simple_Texture2D:

SRCS =     ./samples/gles2_book/Simple_Texture2D/Simple_Texture2D.c
Stencil_Test:

SRCS =     ./samples/gles2_book/Stencil_Test/Stencil_Test.c
Simple_TextureCubemap:

SRCS =     ./samples/gles2_book/Simple_TextureCubemap/Simple_TextureCubemap.c





essl_to_hlsl:

SRCS =     ./src/common/debug.cpp \
    		./samples/translator/translator.cpp

essl_to_glsl:

SRCS =     ./src/common/debug.cpp \
    		./samples/translator/translator.cpp

libEGL:
LIBEGL_EXPORTS;_CRT_SECURE_NO_DEPRECATE;NOMINMAX;_SECURE_SCL=0;
LIBEGL_EXPORTS;_CRT_SECURE_NO_DEPRECATE;NOMINMAX;
SRCS = 	./src/Common/debug.cpp \
	./src/libEGL/Config.cpp \   
	./src/libEGL/libEGL.cpp \  
	./src/libEGL/Surface.cpp \
	./src/libEGL/Display.cpp \  
	./src/libEGL/main.cpp

libGLESv2:

LIBGLESV2_EXPORTS;_CRT_SECURE_NO_DEPRECATE;NOMINMAX;
ANGLE_DISABLE_TRACE;LIBGLESV2_EXPORTS;_CRT_SECURE_NO_DEPRECATE;NOMINMAX;_SECURE_SCL=0;

SRCS = 	../third_party/murmurhash/MurmurHash3.cpp \
	./src/libGLESv2/Buffer.cpp \
    	./src/libGLESv2/Context.cpp \
    	./src/Common/debug.cpp \
	./src/Common/event_tracer.cpp \
	./src/libGLESv2/Fence.cpp \
    	./src/libGLESv2/Float16ToFloat32.cpp \
    	./src/libGLESv2/Framebuffer.cpp \
    	./src/libGLESv2/HandleAllocator.cpp \
    	./src/libGLESv2/libGLESv2.cpp \
    	./src/libGLESv2/main.cpp \
    	./src/libGLESv2/precompiled.cpp
	./src/libGLESv2/Program.cpp \
    	./src/libGLESv2/ProgramBinary.cpp \
    	./src/libGLESv2/Query.cpp \
    	./src/Common/RefCountObject.cpp \
    	./src/libGLESv2/Renderbuffer.cpp \
    	./src/libGLESv2/renderer/Blit.cpp \
    	./src/libGLESv2/renderer/Fence11.cpp \
    	./src/libGLESv2/renderer/Fence9.cpp \
    	./src/libGLESv2/renderer/BufferStorage.cpp \
    	./src/libGLESv2/renderer/BufferStorage11.cpp \
    	./src/libGLESv2/renderer/BufferStorage9.cpp \
    	./src/libGLESv2/renderer/Image.cpp \
    	./src/libGLESv2/renderer/Image9.cpp \
    	./src/libGLESv2/renderer/IndexBuffer.cpp \
    	./src/libGLESv2/renderer/IndexBuffer11.cpp \
    	./src/libGLESv2/renderer/IndexBuffer9.cpp \
    	./src/libGLESv2/renderer/IndexDataManager.cpp \
    	./src/libGLESv2/renderer/ImageSSE2.cpp \
    	./src/libGLESv2/renderer/Image11.cpp \
    	./src/libGLESv2/renderer/IndexRangeCache.cpp \
    	./src/libGLESv2/renderer/InputLayoutCache.cpp \
    	./src/libGLESv2/renderer/Query11.cpp \
    	./src/libGLESv2/renderer/Query9.cpp \
    	./src/libGLESv2/renderer/Renderer.cpp \
    	./src/libGLESv2/renderer/Renderer11.cpp \
    	./src/libGLESv2/renderer/renderer11_utils.cpp \
    	./src/libGLESv2/renderer/Renderer9.cpp \
    	./src/libGLESv2/renderer/renderer9_utils.cpp \
    	./src/libGLESv2/renderer/RenderTarget11.cpp \
    	./src/libGLESv2/renderer/RenderTarget9.cpp \
    	./src/libGLESv2/renderer/RenderStateCache.cpp \
    	./src/libGLESv2/renderer/ShaderExecutable11.cpp \
    	./src/libGLESv2/renderer/ShaderExecutable9.cpp \
    	./src/libGLESv2/renderer/SwapChain11.cpp \
    	./src/libGLESv2/renderer/SwapChain9.cpp \
    	./src/libGLESv2/renderer/TextureStorage.cpp \
    	./src/libGLESv2/renderer/TextureStorage11.cpp \
    	./src/libGLESv2/renderer/TextureStorage9.cpp \
    	./src/libGLESv2/renderer/VertexBuffer.cpp \
    	./src/libGLESv2/renderer/VertexBuffer11.cpp \
    	./src/libGLESv2/renderer/VertexBuffer9.cpp \
    	./src/libGLESv2/renderer/VertexDataManager.cpp \
    	./src/libGLESv2/renderer/VertexDeclarationCache.cpp \
    	./src/libGLESv2/ResourceManager.cpp \
    	./src/libGLESv2/Shader.cpp \
    	./src/libGLESv2/Texture.cpp \
    	./src/libGLESv2/Uniform.cpp \
    	./src/libGLESv2/utilities.cpp

